// <auto-generated />
using System;
using Backend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DuelNexusDbContext))]
    [Migration("20260207153959_DefaultValuesFix")]
    partial class DefaultValuesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.Models.AttackAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttackerCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefenderCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefenderPlayerGameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttackerCardId");

                    b.HasIndex("DefenderCardId");

                    b.HasIndex("DefenderPlayerGameId");

                    b.HasIndex("TurnId", "AttackerCardId")
                        .IsUnique();

                    b.ToTable("AttackActions");
                });

            modelBuilder.Entity("Backend.Data.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EffectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EffectId");

                    b.ToTable("Cards");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Data.Models.CardMovementAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromZone")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameCardId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<int>("ToZone")
                        .HasColumnType("integer");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameCardId");

                    b.HasIndex("TurnId", "GameCardId")
                        .IsUnique();

                    b.ToTable("CardMovementActions");
                });

            modelBuilder.Entity("Backend.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GameRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Backend.Data.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Backend.Data.Models.DeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique();

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("Backend.Data.Models.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Affects")
                        .HasColumnType("integer");

                    b.Property<int?>("Points")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresTarget")
                        .HasColumnType("boolean");

                    b.Property<bool>("TargetsPlayer")
                        .HasColumnType("boolean");

                    b.Property<int?>("Turns")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("Backend.Data.Models.EffectActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EffectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EffectId");

                    b.HasIndex("SourceCardId");

                    b.HasIndex("TurnId", "SourceCardId")
                        .IsUnique();

                    b.ToTable("EffectActivations");
                });

            modelBuilder.Entity("Backend.Data.Models.EffectTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetCardId");

                    b.HasIndex("TargetPlayerId");

                    b.HasIndex("ActivationId", "TargetCardId")
                        .IsUnique();

                    b.ToTable("EffectTargets");
                });

            modelBuilder.Entity("Backend.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Data.Models.GameCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DeckOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("DefensePosition")
                        .HasColumnType("boolean");

                    b.Property<int?>("FieldIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFaceDown")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerGameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Zone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerGameId");

                    b.HasIndex("CardId", "PlayerGameId");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("Backend.Data.Models.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("Backend.Data.Models.PlaceCardAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DefensePosition")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FaceDown")
                        .HasColumnType("boolean");

                    b.Property<int?>("FieldIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameCardId");

                    b.HasIndex("TurnId", "GameCardId")
                        .IsUnique();

                    b.ToTable("PlaceCardActions");
                });

            modelBuilder.Entity("Backend.Data.Models.PlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("Backend.Data.Models.PlayerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("LifePoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("Backend.Data.Models.Turn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivePlayerId");

                    b.HasIndex("GameId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Backend.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Elo")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRoomPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("GameRoomPlayers");
                });

            modelBuilder.Entity("Backend.Data.Models.MonsterCard", b =>
                {
                    b.HasBaseType("Backend.Data.Models.Card");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Backend.Data.Models.SpellCard", b =>
                {
                    b.HasBaseType("Backend.Data.Models.Card");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Backend.Data.Models.TrapCard", b =>
                {
                    b.HasBaseType("Backend.Data.Models.Card");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Backend.Data.Models.AttackAction", b =>
                {
                    b.HasOne("Backend.Data.Models.GameCard", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.GameCard", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderCardId");

                    b.HasOne("Backend.Data.Models.PlayerGame", "DefenderPlayer")
                        .WithMany()
                        .HasForeignKey("DefenderPlayerGameId");

                    b.HasOne("Backend.Data.Models.Turn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("Defender");

                    b.Navigation("DefenderPlayer");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Backend.Data.Models.Card", b =>
                {
                    b.HasOne("Backend.Data.Models.Effect", "Effect")
                        .WithMany()
                        .HasForeignKey("EffectId");

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("Backend.Data.Models.CardMovementAction", b =>
                {
                    b.HasOne("Backend.Data.Models.GameCard", "Card")
                        .WithMany()
                        .HasForeignKey("GameCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.Turn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Backend.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("Backend.Data.Models.GameRoom", "GameRoom")
                        .WithMany()
                        .HasForeignKey("GameRoomId");

                    b.HasOne("Backend.Data.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("Backend.Data.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Backend.Data.Models.Deck", b =>
                {
                    b.HasOne("Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Data.Models.DeckCard", b =>
                {
                    b.HasOne("Backend.Data.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Backend.Data.Models.EffectActivation", b =>
                {
                    b.HasOne("Backend.Data.Models.Effect", "Effect")
                        .WithMany()
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.GameCard", "SourceCard")
                        .WithMany()
                        .HasForeignKey("SourceCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.Turn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("SourceCard");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Backend.Data.Models.EffectTarget", b =>
                {
                    b.HasOne("Backend.Data.Models.EffectActivation", "Activation")
                        .WithMany("Targets")
                        .HasForeignKey("ActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.GameCard", "TargetCard")
                        .WithMany()
                        .HasForeignKey("TargetCardId");

                    b.HasOne("Backend.Data.Models.PlayerGame", "TargetPlayer")
                        .WithMany()
                        .HasForeignKey("TargetPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activation");

                    b.Navigation("TargetCard");

                    b.Navigation("TargetPlayer");
                });

            modelBuilder.Entity("Backend.Data.Models.Game", b =>
                {
                    b.HasOne("Backend.Data.Models.GameRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Backend.Data.Models.GameCard", b =>
                {
                    b.HasOne("Backend.Data.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.PlayerGame", "PlayerGame")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("PlayerGame");
                });

            modelBuilder.Entity("Backend.Data.Models.GameRoom", b =>
                {
                    b.HasOne("Backend.Data.Models.User", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("Backend.Data.Models.PlaceCardAction", b =>
                {
                    b.HasOne("Backend.Data.Models.GameCard", "Card")
                        .WithMany()
                        .HasForeignKey("GameCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.Turn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Backend.Data.Models.PlayerCard", b =>
                {
                    b.HasOne("Backend.Data.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Data.Models.PlayerGame", b =>
                {
                    b.HasOne("Backend.Data.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Data.Models.Turn", b =>
                {
                    b.HasOne("Backend.Data.Models.PlayerGame", "ActivePlayer")
                        .WithMany()
                        .HasForeignKey("ActivePlayerId");

                    b.HasOne("Backend.Data.Models.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePlayer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameRoomPlayer", b =>
                {
                    b.HasOne("Backend.Data.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId");

                    b.HasOne("Backend.Data.Models.GameRoom", "GameRoom")
                        .WithMany("Players")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("GameRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Data.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Backend.Data.Models.EffectActivation", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Backend.Data.Models.Game", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Backend.Data.Models.GameRoom", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Backend.Data.Models.PlayerGame", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
